update_max_values:
  name: update_max_values
  description: Update max values from midnight for all Power Max Tracker instances.
  fields: {}

reset_max_values:
  name: reset_max_values
  description: Update max values to the current month's maximum so far for all Power Max Tracker instances.
  fields: {}
